# These are supported funding model platforms

github: ["Macro303"]
patreon: # Username
open_collective: # Username
ko_fi: "Macro303"
tidelift: # Platform Name / Project Name
community_bridge: # Project Name
liberapay: # Username
issuehunt: # Username
otechie: # Username
custom: []