name: 'Testing'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v3.5.1
        with:
          java-version: 8
          distribution: 'temurin'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build --no-daemon